### ISSUE TITLE
Timezone mismatch

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#171]
## Issue details
Start time in feed:
- `"startDate": "2018-09-11T11:00:00Z"`

Start time in feed converted to BST:
- `2018-09-11T12:00:00`

Start time on website also in BST:
![screen shot 2018-09-11 at 18 13 06](https://user-images.githubusercontent.com/2616208/45375927-59e7af80-b5ee-11e8-8aa1-36a4890194a8.png)

## Sample data
Extracted item from: https://api.englandnetball.co.uk/api/openactive/sessions?afterId=71082&afterTimestamp=1536636724

```
{
  "@context": "https://www.openactive.io/ns/oa.jsonld",
  "type": "Event",
  "identifier": 71350,
  "programme": {
    "type": "Brand",
    "name": "Walking Netball",
    "description": "Walking Netball has evolved from a growing demand for walking sports. Often, one of netball’s strengths is that people never forget playing the sport and the memories as well as the love for the game never leave.\r\n\r\nWalking Netball is a slower version of the game; it is netball, but at a walking pace. The game has been designed so that anyone can play it regardless of age or fitness level.\r\n\r\nFrom those who have dropped out of the sport they love due to serious injury, to those who believed they had hung up their netball trainers many years ago, it really is for everyone.\r\n\r\nWomen the length of the country have begun playing the game of Walking Netball for the fun, laughter and camaraderie the social session brings, as much as the health benefits on offer. It can give those who feel isolated an outlet, provide an activity for those who don’t deem themselves fit enough to run anymore and offer a stepping stone for those looking for a pathway back into netball.",
    "logo": "https://www.englandnetball.co.uk/app/uploads/2016/04/Walking-Netball.jpg",
    "url": "https://www.englandnetball.co.uk/my-game/walking-netball/",
    "beta:video": "https://www.youtube.com/watch?v=qzQfnv7sFPg",
    "category": "Coached Sessions",
    "level": "Beginner"
  },
  "activity": {
    "id": "https://www.openactive.io/activity-list/#aba839fb-5cd2-4042-b651-c09c86bce1e2",
    "type": "Concept",
    "prefLabel": "Walking Netball",
    "inScheme": "https://www.openactive.io/activity-list/activity-list.jsonld"
  },
  "superEvent": {
    "identifier": "WN006115",
    "type": "Event",
    "eventSchedule": {
      "type": "Schedule",
      "endDate": "2018-10-30",
      "frequency": "P14D"
    }
  },
  "eventStatus": "http://schema.org/EventScheduled",
  "location": {
    "type": "Place",
    "name": "Thornaby Pavillion",
    "address": {
      "type": "PostalAddress",
      "postalCode": "TS17 9EW",
      "addressCountry": "GB"
    },
    "geo": {
      "type": "GeoCoordinates",
      "latitude": 54.5386474,
      "longitude": -1.290952
    }
  },
  "startDate": "2018-09-11T11:00:00Z",
  "endDate": "2018-09-11T12:00:00Z",
  "duration": "PT1H",
  "leader": {
    "type": "Person",
    "name": "Liz James",
    "email": "izziescissors@hotmail.co.uk"
  },
  "organizer": {
    "name": "England Netball",
    "url": "https://www.englandnetball.co.uk"
  },
  "url": "https://www.englandnetball.co.uk/?pagename=session&sessionid=[71350&WN006115",
  "sameAs": [
    "https://www.facebook.com/southdurhamandclevelandnetball/",
    " Netball In South Durham & Cleveland @NetballInSDandC"
  ],
  "offer": [
    {
      "type": "Offer",
      "name": "Full price cost",
      "price": "3.50",
      "priceCurrency": "GBP"
    }
  ]
}
```

**Comment by daniel-somersault** [comment]
@nickevansuk This is a glitch on our server that we are implementing a fix for.  This will update all programmes accordingly - we just need to test some more before implementing.

**Comment by daniel-somersault** [comment]
@nickevansuk still waiting on a EN's web provider to get back to me before we can schedule in the fix for this.  The other items have been done and are ready to test again.

**Comment by nickevansuk** [comment]
Thanks @daniel-somersault, have gone through these - good progress.

You can now use https://validator.openactive.io/ to validate your feed, which will make it easier to spot some of these niggling bugs, especially when updating to V2.

**Comment by daniel-somersault** [comment]
@nickevansuk the timezone fix has now been implemented

**Comment by nickevansuk** [comment]
This appears to still be incorrect. I've included a test script here which might help...

Test data:
- First result in https://api.englandnetball.co.uk/api/openactive/sessions?afterId=76866&afterTimestamp=0
- `"startDate": "2018-09-27T19:30:00+01:00", "endDate": "2018-09-27T20:30:00+01:00",`

Test results (see [here](https://jsfiddle.net/nickevansuk/q7x5and0/28/) for test script)
```
Current website: 
  - Feed value: 2018-09-27T19:30:00+01:00
  - Expected: 18:30
  - Actual: 19:30
  - Result: FAIL

Proposed solution A: 
  - Feed value: 2018-09-27T18:30:00+01:00
  - Expected: 18:30
  - Actual: 18:30
  - Result: PASS

Proposed solution B: 
  - Feed value: 2018-09-27T17:30:00Z
  - Expected: 18:30
  - Actual: 18:30
  - Result: PASS
```

**Comment by daniel-somersault** [comment]
@nickevansuk I think this is on the Session Finder tool on EN's website rather than our feed, looks like they aren't adjusting for BST (GMT sessions showing correct time).  I'll get them to have a look.  Our output is correct now though.

**Comment by nickevansuk** [comment]
Glad we spotted that! Will leave this here until everything matches...

**Comment by daniel-somersault** [comment]
@nickevansuk Looks like they have fixed now on the Session Finder website

**Comment by nickevansuk** [comment]
@daniel-somersault It's still not fixed i'm afraid...

This appears to still be incorrect. I've included a test script here which might help...

Test data:
- First result in https://api.englandnetball.co.uk/api/openactive/sessions?afterId=76891&afterTimestamp=0
- `"startDate": "2018-10-24T19:00:00+01:00", "endDate": "2018-10-24T20:00:00+01:00",`
- URL of this result: https://www.englandnetball.co.uk/?pagename=session&sessionid=[76892&B2N006579
- `Time: 18:00 - 19:00`

Test results (see [here](https://jsfiddle.net/nickevansuk/and2c6sx/) for updated test script)
```
Current website: 
  - Feed value: 2018-10-24T19:00:00+01:00
  - Expected: 18:00
  - Actual: 19:00
  - Result: FAIL

Proposed solution A: 
  - Feed value: 2018-10-24T18:00:00+01:00
  - Expected: 18:00
  - Actual: 18:00
  - Result: PASS

Proposed solution B: 
  - Feed value: 2018-09-27T17:00:00Z
  - Expected: 18:00
  - Actual: 18:00
  - Result: PASS
```

**Comment by nickevansuk** [comment]
Suggest that you share this with whoever is doing the implementation: https://youtu.be/-5wpm-gesOY

My advice would be to never try to deal with timezones manually, as they are always more difficult than you expect. Ensure that the implementor is using the most commonly used library available for their language/framework of choice.

**Comment by daniel-somersault** [comment]
@nickevansuk EN have updated that template now so that should now match the output in the api

**Comment by nickevansuk** [comment]
Looks great!
