### ISSUE TITLE
RPDE sort error

### ISSUE THREAD

**Issue by nickevansuk** [openactive/activation#192]
## Issue
https://validator.openactive.io/rpde returns the error:
> When using the Modified Timestamp and ID Ordering Strategy, the combination of afterTimestamp and afterId in the next url must always increase with each new page, as the primary query sorts first by modified and then by id. The next URL of this page is "https://api.runtogether.co.uk/odi/public/courses?afterTimestamp=1539303027160&afterId=442958ab-45dc-43dc-b803-d309eabd705c"

This is most likely due to the IDs being sorted incorrectly in the core query. Check the query matches the below (IDs should be sorted in ascending and not descending order):
```sql
   WHERE (modified = @afterTimestamp
            AND id > @afterId)
      OR (modified > @afterTimestamp)
ORDER BY modified,
         id
```

We also noticed this same issue with the LTA endpoint.

**Comment by nickevansuk** [comment]
Will leave this in QA until this goes live, in order to test properly

**Comment by dolkensp** [comment]
Be sure to use the validator to verify this, as the SQL sort order for GUIDs is not intuitive for most people.

Indeed, this bug was caused by SQL sorting the IDs differently to C# (alphabetical), so we've updated our code to sort the same as SQL.

**Comment by nickevansuk** [comment]
Good to know @dolkensp, will do

**Comment by nickevansuk** [comment]
Running the production endpoint through https://validator.openactive.io/rpde still shows issues with the ordering...
